<center> <font color = #82318E size = 5 face = "微软雅黑" > numpy の 测试 </font> </center>

<center> <font color = #82318E size = 4 face = "微软雅黑" > 1. 常用操作 </font> </center>

In [1]:
import numpy as np

<center> <font color = #82318E size = 3 face = "微软雅黑" > 数据类型 </font> </center>

In [2]:
a = np.array([1.0, 2.0, 3.5], dtype = np.float)
print(a)
print(a.dtype)

a = a.astype(np.int64)
print(a) 
print(a.dtype)

#单行注释可以用 #, 多行注释可以用“”“ ”“” 括起来，或者
#int,int32 : -2e9 ~ 2e9
#int64 : -9e18 ~ 9e18
#uint,uint32 : 0 ~ 4e9
#uint64 : 0 ~ 2e19
#float32 : 2^8.2^-23
#float,float64 : 2^11.2^-52 

[ 1.   2.   3.5]
float64
[1 2 3]
int64


In [39]:
b = np.array([[2.5, 1, 4], [3.5, 8, 7]])
print(b)
print(b.shape)
print(type(b))
print(b.dtype)

[[ 2.5  1.   4. ]
 [ 3.5  8.   7. ]]
(2, 3)
<class 'numpy.ndarray'>
float64


<center> <font color = #82318E size = 3 face = "微软雅黑" > arange 函数 </font> </center>

In [40]:
# arange函数, 左闭右开
np.arange(start = 3, stop = 7, step = 0.5, dtype = np.float64)

array([ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5])

In [41]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [42]:
# 可以只输入一个参数，默认从0开始，默认间隔为1
np.arange(6)

array([0, 1, 2, 3, 4, 5])

<center> <font color = #82318E size = 3 face = "微软雅黑" > linspace 函数 </font> </center>

In [43]:
# linspace函数, 闭区间，但可以指定右区间端点是否取到
print(np.linspace(3, 7, num = 5))

[ 3.  4.  5.  6.  7.]


In [44]:
np.linspace(3, 7, num = 4, endpoint = False)

array([ 3.,  4.,  5.,  6.])

<center> <font color = #82318E size = 3 face = "微软雅黑" > ones zeros eye fromfunction 函数 </font> </center>

In [45]:
c = np.ones((3, 2), dtype = np.float64)
print(c.shape)
'''
数组与矩阵的下标，从0开始
'''
print(c[0][1])

c = c.reshape(1, 2, 3)
print(c.shape)
print(c[0][0][0])


(3, 2)
1.0
(1, 2, 3)
1.0


In [46]:
print(np.zeros((3, 2, 2)))
"""
-----------                --                --                -------3个2*2矩阵
"""
np.array( [[[0, 0], [0, 0]], [[0, 0], [0, 0]], [[0, 0], [0, 0]]] )

[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]


array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [47]:
np.eye(5, 6, k = -2, dtype = np.int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [48]:
np.fromfunction(lambda a, b: a + b, (5, 4), dtype = np.int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

<center> <font color = #82318E size = 3 face = "微软雅黑" > ndarray 操作 </font> </center>

In [49]:
d = np.array([[1, 2, 3], [4, 5, 6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [50]:
d = d.T
print(d)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
d = d.transpose()
print(d)

[[1 2 3]
 [4 5 6]]


In [52]:
d = np.array([[1, 2, 3], [4, 5, 6]], dtype = np.int32)

print(d[0][0].dtype)
print(d.shape)

# 二维矩阵
print(d.ndim)

# 一共有 2*3 = 6 个数
print(d.size)

# 4字节，共6个数，所以一共24字节
print(d.nbytes)
print(' ')

# int32型一个占用4字节（32位, 8bit = 1Byte, 故4字节）
print(d.itemsize)

d.astype(np.float64)

print(d.itemsize)

# 直接 .astype 并不行, 要重新赋值才行
d = d.astype(np.float64)
print(d.itemsize)

int32
(2, 3)
2
6
24
 
4
4
8


<center> <font color = #82318E size = 3 face = "微软雅黑" > 复数操作 </font> </center>

In [53]:
e = np.array([[2+3j, 3+8j], [1j, 4]], dtype = np.complex)
"""
Python中虚数单位是j, 而非i
Python中j不行, 要写1j
"""

print(e.real)
print(e.imag)

[[ 2.  3.]
 [ 0.  4.]]
[[ 3.  8.]
 [ 1.  0.]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > reshape函数 </font> </center>

In [54]:
f = np.eye(4, 3, k = -1, dtype = np.int)
print(f)

np.reshape(f, (2,6))
print(f)

"""
！！！
上面没有输出时没有改变形状，是因为没有覆盖赋值
"""
f = np.reshape(f, (2,6))
print(f)

f = f.reshape(3,4)
print(f)

# 可以由-1补齐, 根据数据量自己计算该维度大小
f = f.reshape(6,-1)
print(f)

[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0 1 0 0]
 [0 1 0 0 0 1]]
[[0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]
[[0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > ravel函数 </font> </center>

In [55]:
g = np.arange(12).reshape(4, 3)
print(g)

# 'C'表示按行展开；'F'表示按列展开
g = np.ravel(g, order = 'C')
print(g)

g = np.arange(12).reshape(4, 3)
print(g)

g = np.ravel(g, order = 'F')
print(g)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  3  6  9  1  4  7 10  2  5  8 11]


In [56]:
g = np.arange(24).reshape(2, 3, 4)
print(g)

h = []
# 现在准备先取第三维，再取第二维，再取最后一维
for k in np.arange(g.shape[2]):
      for j in np.arange(g.shape[1]):
            for i in np.arange(g.shape[0]):
                h.append(g[i][j][k])
print(h)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0, 12, 4, 16, 8, 20, 1, 13, 5, 17, 9, 21, 2, 14, 6, 18, 10, 22, 3, 15, 7, 19, 11, 23]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 轴移动 </font> </center>

In [57]:
i = np.arange(24).reshape(2, 3, 4)
print(i.shape)
print(i)

# moveaxis函数是移动轴函数：初始轴'0', 目标轴'-1'指的是最后一个维度, 即'2'
i = np.moveaxis(i, 0, -1)
print(i.shape)
print(i)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [58]:
i = np.arange(24).reshape(1, 2, 3, 4)
print(i.shape)
print(i)

# moveaxis函数是移动轴函数：初始轴'维度0', 目标轴'-2'指的是倒数第二个维度, 即'维度2'
# 相当于拿出'维度0'这个轴, 剩下的往前一推，然后把'维度0'放在'维度2'这个位置
i = np.moveaxis(i, 0, -2)
print(i.shape)
print(i)

(1, 2, 3, 4)
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
(2, 3, 1, 4)
[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]


 [[[12 13 14 15]]

  [[16 17 18 19]]

  [[20 21 22 23]]]]


In [59]:
i = np.arange(24).reshape(2, 3, 4)
print(i.shape)
print(i)

# swapaxes函数是交换轴函数: 交换'维度0'与'维度2'
i = np.swapaxes(i, 0, 2)
print(i.shape)
print(i)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(4, 3, 2)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [60]:
i = np.arange(24).reshape(1, 2, 3, 4)
print(i.shape)
print(i)

# transpose函数是，全部翻转过来
i = np.transpose(i)
print(i.shape)
print(i)

(1, 2, 3, 4)
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]
(4, 3, 2, 1)
[[[[ 0]
   [12]]

  [[ 4]
   [16]]

  [[ 8]
   [20]]]


 [[[ 1]
   [13]]

  [[ 5]
   [17]]

  [[ 9]
   [21]]]


 [[[ 2]
   [14]]

  [[ 6]
   [18]]

  [[10]
   [22]]]


 [[[ 3]
   [15]]

  [[ 7]
   [19]]

  [[11]
   [23]]]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 类型转换 </font> </center>

In [61]:
j = np.ones((3, 2))
print(j)

# 这里asmatrix函数并没有什么实际作用, 只是在这里向大家展示一下 
j = np.asmatrix(j, dtype = np.float64)
print(j)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 连接 </font> </center>

In [62]:
l = np.ones((2, 2))
m = np.ones((3, 2))
n = np.ones((1, 2))

# axis表示连接轴, '维度0'表示连接后, 行拼在了一起
k = np.concatenate((l, m, n), axis = 0)
print(k)

l = np.ones((3, 1))
m = np.ones((3, 2))
n = np.ones((3, 3))

k = np.concatenate((l, m, n), axis = 1)
print(k)

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 数组堆叠 </font> </center>

In [63]:
m = np.arange(3)
n = np.ones(3)

# axis表示堆叠轴, '维度0'表示堆叠后, 行堆在了一起
k = np.stack((m, n), axis = 0)
print(k)

[[ 0.  1.  2.]
 [ 1.  1.  1.]]


In [64]:
m = np.arange(3)
n = np.ones(3)

# axis表示堆叠轴, '维度1'表示堆叠后, 列堆在了一起
k = np.stack((m, n), axis = 1)
print(k)

k = np.column_stack((m, n))
print(k)

m = np.asmatrix(m)
n = np.asmatrix(n)
k = np.concatenate((m.T, n.transpose()), axis = 1)
print(k)

# 相当于在concatenate函数中, axis选择了'维度1'
k = np.hstack((m.T, np.transpose(n)))
print(k)

"""
以上四者效果是一样哒
值得一提的是
后两种需要先转化为matrix类型, 这是因为一维array是数组类型不支持转置
"""

print()

[[ 0.  1.]
 [ 1.  1.]
 [ 2.  1.]]
[[ 0.  1.]
 [ 1.  1.]
 [ 2.  1.]]
[[ 0.  1.]
 [ 1.  1.]
 [ 2.  1.]]
[[ 0.  1.]
 [ 1.  1.]
 [ 2.  1.]]



<center> <font color = #82318E size = 3 face = "微软雅黑" > 拆分 </font> </center>

In [65]:
o = np.arange(12).reshape(2, 6)
print(o)

#split函数, 第二个参数表示拆分成几个, 第三个参数表示按'维度0'拆分
(p,q) = np.split(ary = o, indices_or_sections = 2 ,axis = 0)
print(p)
print(q)

(p,q) = np.split(o, 2 ,axis = 1)
print(p)
print(q)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[0 1 2 3 4 5]]
[[ 6  7  8  9 10 11]]
[[0 1 2]
 [6 7 8]]
[[ 3  4  5]
 [ 9 10 11]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 删除 </font> </center>

In [66]:
r = np.arange(24).reshape(4, 6)
print(r)

# delete函数表示删除, obj表示删除'索引2', axis表示在'维度0'上删除
r = np.delete(arr = r, obj = 2, axis = 0)
print(r)

r = np.delete(r, np.arange(1,5,step = 2), axis = 1)
print(r)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
[[ 0  2  4  5]
 [ 6  8 10 11]
 [18 20 22 23]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 插入 </font> </center>

In [67]:
u = np.fromfunction(lambda a, b : a + b, (3, 4), dtype = np.int)
print(u)

v = np.array([[3, 2, 1, 0],[4, 3, 2, 1]], dtype = np.int)
print(v)

'''
在'维度0'上, 将v插入到u的'索引1'处 
'''
w = np.insert(arr = u, obj = 1, values = v, axis = 0)
print(w)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]
[[3 2 1 0]
 [4 3 2 1]]
[[0 1 2 3]
 [3 2 1 0]
 [4 3 2 1]
 [1 2 3 4]
 [2 3 4 5]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 附加 </font> </center>

In [68]:
s = np.eye(3, 4)
print(s)
t = np.arange(4).reshape(1, 4)
print(t)

# 相当于insert函数, obj选择了最后一个'索引-1'
# 注意: s与t的规模需对应
s = np.append(arr = s, values = t, axis = 0)
print(s)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[0 1 2 3]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  2.  3.]]


In [69]:
# 一般应用场景, 就是直接将数组连在数组后面
s = np.arange(5)
t = np.arange(3)

s = np.append(s, t)
print(s)

[0 1 2 3 4 0 1 2]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 翻转 </font> </center>

In [70]:
x = np.arange(12).reshape(3, 4)
print(x)

y = np.fliplr(x)
print(y)

y = np.flipud(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 抽签? 抽签! </font> </center>

In [71]:
# 按照概率p在数组a里, 不('False')放回抽取'6'个数
pro = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1], dtype = np.float64)
np.random.choice(a = np.arange(10), size = 8, replace = False, p = pro)

array([7, 0, 3, 5, 8, 6, 1, 4])

In [72]:
np.random.choice(np.arange(10), 1)

array([8])

<center> <font color = #82318E size = 3 face = "微软雅黑" > 正态分布 </font> </center>

In [73]:
# 正态分布 N(mu, sigma)
mu = 0
sigma = 1
np.random.normal(loc = mu, scale = sigma, size = 10)

array([ 0.14509952, -1.46819861,  0.24446   ,  0.28993389,  0.34804353,
        1.28461311, -0.69108163,  0.81203384, -0.24216001, -1.37106198])

In [74]:
np.random.multivariate_normal(mean = np.zeros(2), cov = np.eye(2, 2), size = 10)

array([[ 1.53427619, -0.05481625],
       [ 0.34829756,  0.66931833],
       [ 1.84170414,  1.62337038],
       [-0.34782167,  0.68334497],
       [-0.5346977 , -0.73583048],
       [-1.98101897,  2.01842865],
       [-0.18840164,  0.32614588],
       [-1.20553684, -1.31423707],
       [-0.08389654, -0.67385499],
       [ 0.18406802, -0.7647344 ]])

<center> <font color = #82318E size = 3 face = "微软雅黑" > 均匀分布 </font> </center>

In [75]:
# 均匀分布 从[low,high)中取数, 填充成'(3, 4)'
np.random.uniform(low = -1, high = 1, size = (3, 4))

array([[-0.88746992, -0.98659382, -0.29679926,  0.82429003],
       [-0.0268614 , -0.50619911, -0.74357946, -0.23329985],
       [ 0.85971653, -0.28446644, -0.34286843, -0.41656066]])

<center> <font color = #82318E size = 4 face = "微软雅黑" > 2. 数学函数 </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > 三角函数 </font> </center>

In [76]:
print(np.sin(1/6 * np.pi))
print(np.cos(1/6 * np.pi))
print(np.tan(1/6 * np.pi))
print(np.arcsin(1))
print(np.rad2deg(np.pi))
print(np.deg2rad(180))

0.5
0.866025403784
0.57735026919
1.57079632679
180.0
3.14159265359


<center> <font color = #82318E size = 3 face = "微软雅黑" > 双曲函数 </font> </center>

In [77]:
print(np.tanh(0))

0.0


<center> <font color = #82318E size = 3 face = "微软雅黑" > 数值修约 </font> </center>

In [78]:
# 保留'3'位小数
print(np.round_(1.23456789, 3))

print(' ')
# 四舍五入到整数
print(np.rint(5.5))
print(np.rint(5.48))

print(' ')
# 向0取整
print(np.fix(-2.34))
print(np.fix(2.34))

print(' ')
# 向下取整
print(np.floor(2.34))

# 向上取整
print(np.ceil(2.34))

# 取整数部分
print(np.trunc(2.34))

1.235
 
6.0
5.0
 
-2.0
2.0
 
2.0
3.0
2.0


<center> <font color = #82318E size = 3 face = "微软雅黑" > 矩阵操作 </font> </center>

In [79]:
a = np.arange(12).reshape(3, 4)
print(a)

# 将a的'维度1'上的数乘起来压到剩余维度上, '维度1'上仅剩一数, ('True')保持维度
b = np.prod(a, axis = 1, dtype = np.float, keepdims = True)
print(b)

# NaN视为1
c = np.nanprod(a, axis = 1, dtype = np.float, keepdims = True)
print(c)

# 累积求积
d = np.nancumprod(a, axis = 1, dtype = np.int32)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[    0.]
 [  840.]
 [ 7920.]]
[[    0.]
 [  840.]
 [ 7920.]]
[[   0    0    0    0]
 [   4   20  120  840]
 [   8   72  720 7920]]


In [80]:
a = np.arange(12).reshape(3, 4)
print(a)

# 将a的'维度1'上的数乘起来压到剩余维度上, '维度1'上仅剩一数, ('True')保持维度
b = np.sum(a, axis = 0, dtype = np.float, keepdims = True)
print(b)

# NaN视为0
c = np.nansum(a, axis = 0, dtype = np.float, keepdims = True)
print(c)

# 累积求和
d = np.nancumsum(a, axis = 0, dtype = np.int32)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 12.  15.  18.  21.]]
[[ 12.  15.  18.  21.]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [81]:
a = np.arange(12).reshape(4, 3)
print(a)

# 将'维度0'做'1阶'差分
b = np.diff(a, n = 1, axis = 0)
print(b)

c = np.diff(a, n = 2, axis = 1)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[0]
 [0]
 [0]
 [0]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 指数 </font> </center>

In [82]:
d = np.array([-3, 2], dtype = np.float)
np.exp(d)

array([ 0.04978707,  7.3890561 ])

<center> <font color = #82318E size = 3 face = "微软雅黑" > 对数 </font> </center>

In [83]:
d = np.array([1, 2], dtype = np.int32)
# 以e为底
np.log(d)

array([ 0.        ,  0.69314718])

<center> <font color = #82318E size = 3 face = "微软雅黑" > 算术运算 </font> </center>

In [84]:
a = np.random.choice(np.arange(10), (3, 4))
print(a)

b = np.fromfunction(lambda a, b : a + b + 1, (3, 4), dtype = np.float)
print(b)

[[8 4 5 9]
 [8 6 0 5]
 [6 3 4 7]]
[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]]


In [85]:
'''
------矩阵加法------
'''
c = np.add(a, b)
print(c)


'''
------矩阵减法------
'''
c = np.subtract(a, b)
print(c)


'''
------矩阵各元素求倒数------
Remark: 元素要设成 np.float
'''
c = np.reciprocal(b)
print(c)


'''
------矩阵各元素求负数------
'''
c = np.negative(a)
print(c)


'''
------矩阵对应位置相乘------
'''
c = np.multiply(a, b)
print(c)


'''
------矩阵对应位置相除------
'''
c = np.divide(a, b)
print(c)


'''
------矩阵各元素'2'次幂------
'''
c = np.power(a, 2)
print(c)

[[  9.   6.   8.  13.]
 [ 10.   9.   4.  10.]
 [  9.   7.   9.  13.]]
[[ 7.  2.  2.  5.]
 [ 6.  3. -4.  0.]
 [ 3. -1. -1.  1.]]
[[ 1.          0.5         0.33333333  0.25      ]
 [ 0.5         0.33333333  0.25        0.2       ]
 [ 0.33333333  0.25        0.2         0.16666667]]
[[-8 -4 -5 -9]
 [-8 -6  0 -5]
 [-6 -3 -4 -7]]
[[  8.   8.  15.  36.]
 [ 16.  18.   0.  25.]
 [ 18.  12.  20.  42.]]
[[ 8.          2.          1.66666667  2.25      ]
 [ 4.          2.          0.          1.        ]
 [ 2.          0.75        0.8         1.16666667]]
[[64 16 25 81]
 [64 36  0 25]
 [36  9 16 49]]


In [86]:
a = np.add(np.arange(12), np.ones((1, 12))).reshape(3, 4)
a = np.array(a, dtype = np.int)
print(a)

b = (np.fromfunction(lambda a, b: a + b, (3, 4), dtype = np.int) + np.eye(3, 4)).astype(np.int)
print(b)

'''
------矩阵对应位置除法の余数------
'''
c = np.mod(a, b)
print(c)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 1 2 3]
 [1 3 3 4]
 [2 3 5 5]]
[[0 0 1 1]
 [0 0 1 0]
 [1 1 1 2]]


In [87]:
'''
--均为对应位置的操作--
'''
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)

[[ 2  3  5  7]
 [ 6  9 10 12]
 [11 13 16 17]]
[[0 1 1 1]
 [4 3 4 4]
 [7 7 6 7]]
[[ 1  2  6 12]
 [ 5 18 21 32]
 [18 30 55 60]]
[[ 1.          2.          1.5         1.33333333]
 [ 5.          2.          2.33333333  2.        ]
 [ 4.5         3.33333333  2.2         2.4       ]]
[[1 2 1 1]
 [5 2 2 2]
 [4 3 2 2]]


In [88]:
e = np.array([[0.5, -2.75], [1.25, 6]], dtype = np.float)

'''
------向0取整后, 分离小数部分和整数部分------
'''
f,g = np.modf(e)
print(f)
print(g)

[[ 0.5  -0.75]
 [ 0.25  0.  ]]
[[ 0. -2.]
 [ 1.  6.]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 矩阵运算 </font> </center>

In [89]:
a = np.array([[1, 2], [3, 4]], dtype = np.int)
print(a)
b = np.array([[1, 1], [1, 2]], dtype = np.int)
print(b)

# 矩阵乘法
print(np.dot(a,b))

# Kronecker乘积
print(np.kron(a,b))

[[1 2]
 [3 4]]
[[1 1]
 [1 2]]
[[ 3  5]
 [ 7 11]]
[[1 1 2 2]
 [1 2 2 4]
 [3 3 4 4]
 [3 6 4 8]]


In [90]:
c = np.array([1, -1, 2], dtype = np.int)
print(c)
d = np.array([1, 2, 3], dtype = np.int)
print(d)

# 内积
print(np.inner(c,d))
# 外积
print(np.outer(c,d))

[ 1 -1  2]
[1 2 3]
5
[[ 1  2  3]
 [-1 -2 -3]
 [ 2  4  6]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 复数操作 </font> </center>

In [91]:
e = 1+1j
print(np.real(e), np.imag(e))
print(np.angle(e))
print(np.conj(e)) 
print(np.abs(e))

1.0 1.0
0.785398163397
(1-1j)
1.41421356237


<center> <font color = #82318E size = 3 face = "微软雅黑" > 其他数学函数 </font> </center>

In [92]:
print(np.sqrt(4))
print(np.square(4))
print(np.cbrt(4))
print(np.abs(-4))
print(np.sign(-4))

2.0
16
1.58740105197
4
-1


<center> <font color = #82318E size = 3 face = "微软雅黑" > 矩阵分解 </font> </center>

In [93]:
A = np.fromfunction(lambda a, b : a * b , (3, 3), dtype = np.float64) + np.eye(3, 3)
print(A)

'''
------Cholesky分解(A = np.dot(L, L.T))------
'''
L = np.linalg.cholesky(A)
print(L)
print(A - np.dot(L, L.transpose()))

'''
------特征值与特征向量------
'''
lam, vec= np.linalg.eigh(A)
print(lam)
print(vec)

for i in np.arange(np.size(lam)):
    print(np.dot(A,vec[i].T) - lam[i] * vec[i].T)

    
'''
------行列式------
'''
print(np.linalg.det(A))


'''
------逆------
'''
print(np.linalg.inv(A))


'''
------Moore-Penrose 广义逆------
小于'1e-15'的奇异值，会被视为0
'''
print(np.linalg.pinv(A, rcond = 1e-15))



[[ 1.  0.  0.]
 [ 0.  2.  2.]
 [ 0.  2.  5.]]
[[ 1.          0.          0.        ]
 [ 0.          1.41421356  0.        ]
 [ 0.          1.41421356  1.73205081]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -4.44089210e-16   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]
[ 1.  1.  6.]
[[ 1.          0.          0.        ]
 [ 0.         -0.89442719  0.4472136 ]
 [ 0.          0.4472136   0.89442719]]
[ 0.  0.  0.]
[  0.00000000e+00   0.00000000e+00   1.66533454e-16]
[ 0.  0.  0.]
6.0
[[ 1.          0.          0.        ]
 [ 0.          0.83333333 -0.33333333]
 [ 0.         -0.33333333  0.33333333]]
[[ 1.          0.          0.        ]
 [ 0.          0.83333333 -0.33333333]
 [ 0.         -0.33333333  0.33333333]]


<center> <font color = #82318E size = 4 face = "微软雅黑" > 3. 切片与索引 </font> </center>

<center> <font color = #82318E size = 3 face = "微软雅黑" > list与arrayの取数 </font> </center>

In [94]:
a = np.arange(12).reshape(3, 4)
print(type(a))
print(a)
print(a[1][0])
print(a[1, 0])
print(a[[0, 1, 2], [3, 2,  -1]])
# numpy.ndarray 还支持这种'维度0'上取'0 1 2', '维度1'上取'3 2 -1', 
# 即 a[0][3] a[1][2] a[2][3] 这3个数


<class 'numpy.ndarray'>
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4
4
[ 3  6 11]


In [1]:
b = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
print(type(b))
print(b)
print(b[1][0])
# list 不支持 b[1, 0] 这种取数方式

<class 'list'>
[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
4


<center> <font color = #82318E size = 3 face = "微软雅黑" > 切片 </font> </center>

In [96]:
c = np.arange(1, 24, 2).reshape(3, 4)
print(c)


'''
------Ndarray[start:stop:step]------
按照[start,stop), 间隔为step
'''
print(c[0:3:1, ::])
print(c[[0, 1], ::2])

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[ 1  5]
 [ 9 13]]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 排序 </font> </center>

In [97]:
d = np.random.choice(np.arange(1, 13), size = 12, replace = False).reshape(3, 4)
print(d)

[[10  1  5  7]
 [ 2  9 11  6]
 [12  3  8  4]]


In [98]:
'''
按照 小 -> 大 の顺序, 沿'维度0'做快速排序, 使'维度0'有序
'quicksort'--快速排序
'mergesort'--归并排序
'heapsort'--堆排序
'''
print(np.sort(d, axis = 0, kind = 'quicksort'))

[[ 2  1  5  4]
 [10  3  8  6]
 [12  9 11  7]]


In [99]:
stru = [('name', 'S3'), ('height', float), ('age', int)]
values = [('A', 1.8, 41), ('Bb', 1.9, 38), ('CcCc', 1.7, 38)]
'''
这种用法, 先声明一个 dtype, 
然后按照 order 中规定先'age', 若相同则考虑'height', 由 小 -> 大 排序 
'''

e = np.array(values, dtype = stru)
print(np.sort(e, order = ['age', 'height']))

[(b'CcC',  1.7, 38) (b'Bb',  1.9, 38) (b'A',  1.8, 41)]


<center> <font color = #82318E size = 3 face = "微软雅黑" > 搜索 </font> </center>

In [3]:
f = np.random.normal(loc = 0, scale = 1, size = (3, 4))
f[::2, ::2] = np.nan
print(f)

[[        nan -3.58280261         nan -0.91930665]
 [-0.67561271  0.21017548 -1.82386155  0.26272452]
 [        nan -1.79368552         nan -1.20576508]]


In [5]:
'''
忽略nan, 
沿着'维度0'搜索(这么理解, 返回の值是'维度0'の), 
返回最小值所在的索引
'''
i = np.nanargmin(f, axis = 0)
print(i)

for j in np.arange(f.shape[1]):
    print(f[i[j]][j])

'''
亦可如此表述
'''
print(f[i, np.arange(f.shape[1])])

[1 0 1 2]
-0.675612705873
-3.58280260832
-1.82386154578
-1.20576507896
[-0.67561271 -3.58280261 -1.82386155 -1.20576508]


In [102]:
print(np.arange(f.shape[0]))
print(np.nanargmax(f, axis = 1))
print(f[np.arange(f.shape[0]), np.nanargmax(f, axis = 1)])

[0 1 2]
[1 1 3]
[ 1.01442652  1.37198143  0.44398359]


In [103]:
B = np.fliplr(np.arange(1, 24, step = 2, dtype = np.int).reshape(3, 4))
print(B)

print(B > 20)
print(np.where(B > 20))
print(B[np.where(B > 20)])

'''
这个有点像以前学的 C 里面的那个惟一的三目运算符(条件运算符 ? :)
条件取真，则赋'B'的值, 否则赋'0'
'''
print(np.where(B > 20, B, np.zeros((3,4), dtype = np.int32)))
print(np.where(B > 20, B, 0))

[[ 7  5  3  1]
 [15 13 11  9]
 [23 21 19 17]]
[[False False False False]
 [False False False False]
 [ True  True False False]]
(array([2, 2]), array([0, 1]))
[23 21]
[[ 0  0  0  0]
 [ 0  0  0  0]
 [23 21  0  0]]
[[ 0  0  0  0]
 [ 0  0  0  0]
 [23 21  0  0]]


In [104]:
cond = np.mod(B, 3) == 0
print(cond)

'''
返回满足条件'cond'的元素
'''
print(np.extract(cond, B))
print(B[cond])

C = np.fromfunction(lambda a, b : a, shape = B.shape, dtype = np.int32)
D = np.fromfunction(lambda a, b : b, (3,4), dtype = np.int)
print(C)
print(D)
print(C[cond], D[cond])
print(B[C[cond], D[cond]])

[[False False  True False]
 [ True False False  True]
 [False  True False False]]
[ 3 15  9 21]
[ 3 15  9 21]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[0 1 1 2] [2 0 3 1]
[ 3 15  9 21]


<center> <font color = #82318E size = 3 face = "微软雅黑" > numpy 这个 module 真 · 学了好久 </font> </center>
<center> <font color = #82318E size = 3 face = "微软雅黑" > 但 numpy 真 · 强大: 基本可以实现Matlabの大部分功能啦~ </font> </center>
<center> <font color = #82318E size = 3 face = "微软雅黑" > By the way,
https://docs.scipy.org/doc/numpy/genindex.html 这是手册的网址, 超级有用~ </font> </center>